### ISSUE TITLE
Currency bug: Can you change this plugin so it will honor the currency setting from Woocommerce?

### ISSUE THREAD

**Issue by aram23** [sygency/woocommerce-free-shipping-notification#1]
I Use Euros in my shop, yet your shipping notification uses a $ - US dollar sign. Can this be changed?

![screen shot 2015-09-09 at 15 52 33](https://cloud.githubusercontent.com/assets/13018183/9763614/d8a1ed04-570a-11e5-92f2-be3cb9f262f2.png)

**Comment by werbensmitty** [comment]
hey, thanks for this great plugin. I found a bug: amount shows very long numbers. is there also a way to show a success message when the specified amount is reached? thanks and keep up the good work.
![tolong](https://cloud.githubusercontent.com/assets/16802562/12455350/9600e190-bf9b-11e5-8203-c13b95cd5b66.PNG)

**Comment by AivarasZelba** [comment]
Fixed Both Issues. Update to 1.2 Plugin version.
Thanks for a feedback.
